version: '3'

services:
  freeradius:
    image: wellsgz/docker-freeradius
    container_name: freeradius
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/wells/data/freeradius/clients.conf:/etc/raddb/clients.conf
      - /home/wells/data/freeradius/radiusd.conf:/etc/raddb/radiusd.conf
      - /home/wells/data/freeradius/authorize:/etc/raddb/mods-config/files/authorize
      - /home/wells/data/freeradius/sites-enabled:/etc/raddb/sites-enabled
      - /home/wells/data/freeradius/certs:/etc/raddb/certs
    environment:
      - TZ=Asia/Hong_Kong
      #- RADIUSD_OPTS=-xx # Enable this for FreeRadius extra log verbosity/degub
